---
- hosts: datacenter
  become: 'True'
  gather_facts: 'False'

  handlers:
    - name: apply hostname
      command: hostname -F /etc/hostname
      
    - name: reload networking
      command: "ifreload -a"

    - name: reload frr
      service: name=frr state=restarted

    - name: reload fanout
      service: name=opx-create-interface state=restarted

  roles:
    - interfaces_fanout 
    - interfaces
    - frr


