---
- name: Check if FRR Package is installed
  shell: dpkg -s frr | grep 'install ok installed'
  register: is_installed
  failed_when: no
  changed_when: no

- name: Remove Quagga
  apt:
    name: quagga 
    state: absent
  when: is_installed.rc != 0

- name: Install dependency for FRR
  apt:
    name: libc-ares2 
    update_cache: yes 
    state: latest
  when: is_installed.rc != 0

- name: Install FRR .deb package
  apt:
    deb: http://192.168.114.200/onie_image/frr_3.0.2-1-debian8.1_amd64.deb
  when: is_installed.rc != 0   

- name: ensure FRR is running
  service: name=frr enabled=yes state=started

- name: write the FRR daemons settings
  template: src=templates/daemons dest=/etc/frr/daemons
  notify: reload frr

- name: write the FRR config file
  template: src=templates/frr.j2 dest=/etc/frr/frr.conf
  notify:
    - reload frr
