---
loopback: 10.0.0.3/32

bgp_fabric:
  asn: 64701
  router_id: 10.0.0.3
  neighbor:
    - e101-006-0
    - e101-014-0

interfaces_fanout:
   e101-001-0:
    fanout: 4x1
    speed: 10G

interfaces:
  e101-006-0:
    alias: spine1
    address: "{{ loopback }}"

  e101-014-0:
    alias: spine2
    address: "{{ loopback }}"
    
  e101-001-1:
    alias: server1
    address: 10.1.1.1/24
