---
loopback: 10.0.0.2/32

bgp_fabric:
  asn: 64600
  router_id: 10.0.0.2
  neighbor:
    - e101-014-0
    - e101-016-0
    - e101-032-0
    
interfaces:
  e101-014-0:
    alias: leaf1
    address: "{{ loopback }}"
    link_speed: 100000

  e101-016-0:
    alias: leaf2
    address: "{{ loopback }}"
    link_speed: 100000

  e101-032-0:
    alias: leaf3
    address: "{{ loopback }}" 
    link_speed: 40000