---
loopback: 10.0.0.2/32

bgp_fabric:
  asn: 64600
  router_id: 10.0.0.2
  neighbor:
    - e101-014-0
    - e101-016-0
    - e101-032-1

interfaces_fanout:
   e101-032-0:
    fanout: 1x1
    speed: 40G
 
interfaces:
  e101-014-0:
    alias: leaf1
    address: "{{ loopback }}"

  e101-016-0:
    alias: leaf2
    address: "{{ loopback }}"

  e101-032-1:
    alias: leaf3
    address: "{{ loopback }}" 